FROM node:22-alpine
WORKDIR /app
ARG BUILDTIME=2026-05-29-v4
COPY apps/api/package.json ./
RUN npm install --legacy-peer-deps --ignore-scripts
COPY apps/api/tsconfig.json apps/api/tsconfig.build.json apps/api/nest-cli.json ./
COPY apps/api/src ./src
RUN npx nest build
EXPOSE 8080
CMD ["node", "dist/main.js"]
