import React from 'react';
import { LiveHostBottomLayer } from '@/features/live/host/components/LiveHostBottomLayer';
import { LiveHostMessagingPanelSlot } from '@/features/live/host/components/LiveHostMessagingPanelSlot';
import { LiveHostStudioSettingsPanelSlot } from '@/features/live/host/components/LiveHostStudioSettingsPanelSlot';

/**
 * Couche sous la grille live : overlays bas, messagerie, panneau réglages studio.
 */
export function LiveHostLivePostGridSlots(p) {
  return (
    <>
      <LiveHostBottomLayer
        phase={p.phase}
        isGuestUi={p.isGuestUi}
        lhStageFocusLayout={p.lhStageFocusLayout}
        lhLayoutCompact={p.lhLayoutCompact}
        liveLeftRailOpen={p.liveLeftRailOpen}
        liveRightRailOpen={p.liveRightRailOpen}
        setLiveLeftRailOpen={p.setLiveLeftRailOpen}
        setLiveRightRailOpen={p.setLiveRightRailOpen}
        ambientTracks={p.ambientTracks}
        ambientMasterVolume={p.ambientMasterVolume}
        micOn={p.micOn}
        liriAudioScenes={p.liriAudioScenes}
        guestLiriAudioSmartboard={p.guestLiriAudioSmartboard}
        guestLiriAudioSceneName={p.guestLiriAudioSceneName}
        user={p.user}
        sessionCommFlags={p.sessionCommFlags}
        guestProctorHistoryOpen={p.guestProctorHistoryOpen}
        setGuestProctorHistoryOpen={p.setGuestProctorHistoryOpen}
        guestProctorOwnLoading={p.guestProctorOwnLoading}
        guestProctorOwnRows={p.guestProctorOwnRows}
        fetchGuestProctorOwnHistory={p.fetchGuestProctorOwnHistory}
        debateArena={p.debateArena}
        debateVoteBusy={p.debateVoteBusy}
        setDebateVoteBusy={p.setDebateVoteBusy}
        refreshDebateRounds={p.refreshDebateRounds}
        debateLiveVoteCounts={p.debateLiveVoteCounts}
        guestProctorModalOpen={p.guestProctorModalOpen}
        setGuestProctorModalOpen={p.setGuestProctorModalOpen}
        acceptGuestProctorConsent={p.acceptGuestProctorConsent}
        navigate={p.navigate}
        mobileCameraLinkOpen={p.mobileCameraLinkOpen}
        setMobileCameraLinkOpen={p.setMobileCameraLinkOpen}
        mobileCameraLinkLoading={p.mobileCameraLinkLoading}
        mobileCameraLinkErr={p.mobileCameraLinkErr}
        mobileCameraJoinUrl={p.mobileCameraJoinUrl}
        mobileCameraLinkExpires={p.mobileCameraLinkExpires}
        toast={p.toast}
        modal={p.modal}
        setModal={p.setModal}
        roomRef={p.roomRef}
        promotedId={p.promotedId}
        setPromotedId={p.setPromotedId}
        setAntennaSoloMode={p.setAntennaSoloMode}
        applyHostArenaLayoutMode={p.applyHostArenaLayoutMode}
        memberModalAllowSchoolLife={p.memberModalAllowSchoolLife}
        muteParticipant={p.muteParticipant}
        kickParticipant={p.kickParticipant}
        broadcastHostCameraCommand={p.broadcastHostCameraCommand}
        sessionId={p.sessionId}
        whisperThreads={p.whisperThreads}
        sendWhisper={p.sendWhisper}
        memberModalWhisperPickable={p.memberModalWhisperPickable}
        liveParticipants={p.liveParticipants}
        guestNeuronqPanelOpen={p.guestNeuronqPanelOpen}
        setGuestNeuronqPanelOpen={p.setGuestNeuronqPanelOpen}
        debateNeuronqEnabled={p.debateNeuronqEnabled}
        sessionQuickIaFlags={p.sessionQuickIaFlags}
        guestNeuronqVolets={p.guestNeuronqVolets}
        setGuestNeuronqVolets={p.setGuestNeuronqVolets}
        guestNeuronqReformulated={p.guestNeuronqReformulated}
        setGuestNeuronqReformulated={p.setGuestNeuronqReformulated}
        neuronqReformulating={p.neuronqReformulating}
        neuronqReformulateGuest={p.neuronqReformulateGuest}
        guestNeuronqCombinedRaw={p.guestNeuronqCombinedRaw}
        submitGuestNeuronq={p.submitGuestNeuronq}
        neuronqGuestSubmitting={p.neuronqGuestSubmitting}
        asideMedia={p.asideMedia}
        isHostUser={p.isHostUser}
        forumTarget={p.forumTarget}
        longiaHubOpen={p.longiaHubOpen}
        setLongiaHubOpen={p.setLongiaHubOpen}
        liveHostLongiaSignalHub={p.liveHostLongiaSignalHub}
        longiaHubDrawerWidthPx={p.longiaHubDrawerWidthPx}
        toggleLayoutPreviewHubPanel={p.toggleLayoutPreviewHubPanel}
        longiaSignalSubDrawer={p.longiaSignalSubDrawer}
      />
      <LiveHostMessagingPanelSlot
        showMessagingPanel={p.showMessagingPanel}
        setShowMessagingPanel={p.setShowMessagingPanel}
        forumTarget={p.forumTarget}
        setForumTarget={p.setForumTarget}
        forumInput={p.forumInput}
        setForumInput={p.setForumInput}
        activeMembers={p.activeMembers}
        chatMessages={p.chatMessages}
        whisperThreads={p.whisperThreads}
        user={p.user}
        isGuestUi={p.isGuestUi}
        sessionCommFlags={p.sessionCommFlags}
        guestCapabilityCaps={p.guestCapabilityCaps}
        teacherId={p.teacherId}
        sendChatMessage={p.sendChatMessage}
        sendWhisper={p.sendWhisper}
        toast={p.toast}
        liveKitMediaEpoch={p.liveKitMediaEpoch}
        livekitParticipantsMap={p.livekitParticipantsMap}
        phase={p.phase}
        searchQuery={p.searchQuery}
        setSearchQuery={p.setSearchQuery}
        searchResults={p.searchResults}
        setModal={p.setModal}
        liveStripDockMembers={p.liveStripDockMembers}
        promotedId={p.promotedId}
        sessionId={p.sessionId}
        eleveAppChatUrl={p.eleveAppChatUrl}
        memberVideoPreview={p.memberVideoPreview}
        setMemberVideoPreview={p.setMemberVideoPreview}
        isHostUser={p.isHostUser}
        asideMedia={p.asideMedia}
        hostMonitorBus={p.hostMonitorBus}
      />
      <LiveHostStudioSettingsPanelSlot
        showSettings={p.showSettings}
        setShowSettings={p.setShowSettings}
        isGuestUi={p.isGuestUi}
        phase={p.phase}
        user={p.user}
        sessionId={p.sessionId}
        sessionGuestPermissions={p.sessionGuestPermissions}
        handleGuestPermissionsChange={p.handleGuestPermissionsChange}
        livekitParticipantsMap={p.livekitParticipantsMap}
        cameraOn={p.cameraOn}
        liveKitMediaEpoch={p.liveKitMediaEpoch}
        videoFxActive={p.videoFxActive}
        videoFilterCSS={p.videoFilterCSS}
        videoBeauty={p.videoBeauty}
        setVideoBeauty={p.setVideoBeauty}
        videoChromaKey={p.videoChromaKey}
        handleArenaChromaKeyChange={p.handleArenaChromaKeyChange}
        videoChromaColor={p.videoChromaColor}
        setVideoChromaColor={p.setVideoChromaColor}
        videoChromaSens={p.videoChromaSens}
        setVideoChromaSens={p.setVideoChromaSens}
        videoBlur={p.videoBlur}
        setVideoBlur={p.setVideoBlur}
        videoVbg={p.videoVbg}
        handleArenaVbgChange={p.handleArenaVbgChange}
        videoCustomBgUrl={p.videoCustomBgUrl}
        setVideoCustomBgUrl={p.setVideoCustomBgUrl}
        videoBrightness={p.videoBrightness}
        setVideoBrightness={p.setVideoBrightness}
        videoContrast={p.videoContrast}
        setVideoContrast={p.setVideoContrast}
        videoSaturation={p.videoSaturation}
        setVideoSaturation={p.setVideoSaturation}
        videoHue={p.videoHue}
        setVideoHue={p.setVideoHue}
        micGain={p.micGain}
        setMicGain={p.setMicGain}
        noiseReduction={p.noiseReduction}
        setNoiseReduction={p.setNoiseReduction}
        liriAudioMode={p.liriAudioMode}
        setLiriAudioMode={p.setLiriAudioMode}
        liriClarity={p.liriClarity}
        setLiriClarity={p.setLiriClarity}
        liriReverb={p.liriReverb}
        setLiriReverb={p.setLiriReverb}
        liriCompression={p.liriCompression}
        setLiriCompression={p.setLiriCompression}
        liriGate={p.liriGate}
        setLiriGate={p.setLiriGate}
        liriLimiter={p.liriLimiter}
        setLiriLimiter={p.setLiriLimiter}
        liriAudioLevels={p.liriAudioLevels}
        videoDevices={p.videoDevices}
        audioDevices={p.audioDevices}
        activeVideoId={p.activeVideoId}
        activeAudioId={p.activeAudioId}
        switchVideoDevice={p.switchVideoDevice}
        switchAudioDevice={p.switchAudioDevice}
        arenaHostAlertSoundOn={p.arenaHostAlertSoundOn}
        setArenaHostAlertSoundOn={p.setArenaHostAlertSoundOn}
        forumTarget={p.forumTarget}
        asideMedia={p.asideMedia}
        hostMonitorBus={p.hostMonitorBus}
        ambientTracks={p.ambientTracks}
        ambientMasterVolume={p.ambientMasterVolume}
        setAmbientMasterVolume={p.setAmbientMasterVolume}
        smartboardSceneFlags={p.smartboardSceneFlags}
        handleQuickSmartboardSceneToggle={p.handleQuickSmartboardSceneToggle}
        sessionQuickIaFlags={p.sessionQuickIaFlags}
        handleQuickIaToggle={p.handleQuickIaToggle}
        sessionCommFlags={p.sessionCommFlags}
        handleQuickCommToggle={p.handleQuickCommToggle}
        setShowMessagingPanel={p.setShowMessagingPanel}
        openLongiaHubControlMesh={p.openLongiaHubControlMesh}
        hostMultilang={p.hostMultilang}
        setHostMultilangField={p.setHostMultilangField}
        proctorCamHistoryRows={p.proctorCamHistoryRows}
        proctorCamHistoryLoading={p.proctorCamHistoryLoading}
        fetchProctorCamHistory={p.fetchProctorCamHistory}
      />
    </>
  );
}
