import React, { forwardRef } from 'react';
import { LiveGuestLeftRail } from '@/features/live/host/components/LiveGuestLeftRail';
import { LiveHostLeftRail } from '@/features/live/host/components/LiveHostLeftRail';
import { LiveHostRightColumn } from '@/features/live/host/components/LiveHostRightColumn';

/**
 * Grille live principale : rail gauche (hôte ou invité) | slot centre (`children`, ex. `LiveHostLiveCenterColumn`) | rail droit.
 */
export const LiveHostLiveGridShell = forwardRef(function LiveHostLiveGridShell(p, ref) {
  const {
    hostLiveGridStyle,
    isGuestUi,
    leftColRef,
    rightColRef,
    children,
    hostCompactColOrder,
    liveShell,
    liveLeftRailCollapsedStrip,
    longiaHubPushesLayout,
    lhLayoutCompact,
    liveLeftRailOpen,
    setLiveLeftRailOpen,
    phase,
    meshPanelOpen,
    setMeshPanelOpen,
    setLongiaSignalSubDrawer,
    openLongiaHubControlMesh,
    openLongiaHubCoachPanel,
    longiaHubOpen,
    longiaSignalSubDrawer,
    lhStageFocusLayout,
    sessionId,
    sessionTitle,
    user,
    onlineMemberCount,
    liveDuration,
    curEtape,
    waitingEntries,
    approveWaiting,
    rejectWaiting,
    openLongiaHubWaitingRoom,
    liveHostActivityBadges,
    liveLeftGuestCollapsedStrip,
    liveParticipants,
    sessionFormationId,
    liveRightRailCollapsedStrip,
    liveRightGuestCollapsedStrip,
    liveRightRailOpen,
    setLiveRightRailOpen,
    guestCapabilityCaps,
    onRightScroll,
    hostLiveKitParticipant,
    liveKitMediaEpoch,
    guestMembersGridSelf,
    guestClassmatesPeers,
    guestNotesCurrentSceneRef,
    onGuestCaptureSmartboard,
    onGuestNotesJumpToScene,
    liveMediaCheck,
    liveMediaDiagTick,
    roomRef,
    guestJoyKitDrive,
    tryStartLiveKitPlayback,
    antennaSoloMode,
    setAntennaSoloMode,
    setPromotedId,
    arenaHostCameraCenter,
    lhHostShowsRemoteMain,
    rightRailShowsLocalHost,
    setHostRightRailLocalVideoOpen,
    showHostRightRailVideoFrame,
    hostVidHeight,
    videoFxActive,
    videoFilterCSS,
    arenaLayoutMode,
    applyHostArenaLayoutMode,
    lhMainRemoteParticipant,
    livekitParticipantsMap,
    cameraOn,
    promotedId,
    hostRightRailVideoIsCenterCameraOnly,
    guestMicLocked,
    toggleMic,
    micOn,
    guestCamLocked,
    toggleCamera,
    guestScreenShareLocked,
    toggleScreenShare,
    sharingScreen,
    debateArena,
    liriAudioScenes,
    liriAudioInitialSceneIndex,
    persistLiriSceneIndex,
    debateModBusy,
    debatePatch,
    debateAiWeightPctDisplay,
    onDebateAiWeightRangeChange,
    debateCurrentRoundStatus,
    debateOpenVoting,
    debateCloseVoting,
    debateLiveVoteCounts,
    debateAiJudgeBusy,
    debateRunAiJudge,
    debateAiReportPreview,
    recording,
    recError,
    stopRecording,
    setRecError,
    hostBoardRightRailTools,
    hostWbToolsRail,
    hostWhiteboardPagingForRail,
    mmCardVisible,
    setMmCardVisible,
    mmView,
    setMmView,
    step,
    stepCount,
    activeEtapes,
    gotoStep,
    sessionCommFlags,
    guestMultilangConfig,
    guestLivekitInterpreterParticipants,
    guestLivekitInterpreterVolume,
    setGuestLivekitInterpreterVolume,
    guestMultilangViewLang,
    setGuestMultilangViewLang,
    guestMultilangRolling,
    guestTeacherTranscript,
    guestTeacherTranscriptPartial,
    supabase,
    chatMessages,
    publishGuestLongiaBusEvent,
    guestLongiaSessionDigests,
    toast,
    guestMultilangBrowserTtsOn,
    setGuestMultilangBrowserTtsOnPersist,
    guestMultilangEdgeTtsOn,
    setGuestMultilangEdgeTtsOnPersist,
    assertGuestLongiaSignal,
    guestMeshGrant,
    guestMeshRemainSec,
    guestMediaDrive,
    msMode,
    setMsMode,
    nqAnalysis,
    msBody,
    msTyped,
  } = p;

  return (
    <div
      ref={ref}
      data-lh-host-mobile-mirror="1"
      className="min-h-0 min-w-0 max-w-full flex-1"
      style={hostLiveGridStyle}
    >
      {!isGuestUi ? (
        <LiveHostLeftRail
          ref={leftColRef}
          hostCompactColOrder={hostCompactColOrder}
          liveShell={liveShell}
          liveLeftRailCollapsedStrip={liveLeftRailCollapsedStrip}
          longiaHubPushesLayout={longiaHubPushesLayout}
          lhLayoutCompact={lhLayoutCompact}
          liveLeftRailOpen={liveLeftRailOpen}
          setLiveLeftRailOpen={setLiveLeftRailOpen}
          phase={phase}
          meshPanelOpen={meshPanelOpen}
          setMeshPanelOpen={setMeshPanelOpen}
          setLongiaSignalSubDrawer={setLongiaSignalSubDrawer}
          openLongiaHubControlMesh={openLongiaHubControlMesh}
          openLongiaHubCoachPanel={openLongiaHubCoachPanel}
          longiaHubOpen={longiaHubOpen}
          longiaSignalSubDrawer={longiaSignalSubDrawer}
          lhStageFocusLayout={lhStageFocusLayout}
          sessionId={sessionId}
          sessionTitle={sessionTitle}
          user={user}
          onlineMemberCount={onlineMemberCount}
          liveDuration={liveDuration}
          curEtape={curEtape}
          waitingEntries={waitingEntries}
          activityBadges={liveHostActivityBadges}
          onApproveWaiting={(entryId) => {
            void approveWaiting(entryId);
          }}
          onRejectWaiting={(entryId) => {
            void rejectWaiting(entryId);
          }}
          onOpenLongiaWaiting={openLongiaHubWaitingRoom}
        />
      ) : (
        <LiveGuestLeftRail
          hostCompactColOrder={hostCompactColOrder}
          liveShell={liveShell}
          liveLeftGuestCollapsedStrip={liveLeftGuestCollapsedStrip}
          lhLayoutCompact={lhLayoutCompact}
          liveLeftRailOpen={liveLeftRailOpen}
          phase={phase}
          lhStageFocusLayout={lhStageFocusLayout}
          liveDuration={liveDuration}
          curEtape={curEtape}
          liveParticipants={liveParticipants}
          sessionFormationId={sessionFormationId}
          onOpen={() => setLiveLeftRailOpen(true)}
          onClose={() => setLiveLeftRailOpen(false)}
        />
      )}

      {children}

      <LiveHostRightColumn
        ref={rightColRef}
        isGuestUi={isGuestUi}
        lhLayoutCompact={lhLayoutCompact}
        hostCompactColOrder={hostCompactColOrder}
        liveShell={liveShell}
        liveRightRailCollapsedStrip={liveRightRailCollapsedStrip}
        liveRightGuestCollapsedStrip={liveRightGuestCollapsedStrip}
        lhStageFocusLayout={lhStageFocusLayout}
        liveRightRailOpen={liveRightRailOpen}
        setLiveRightRailOpen={setLiveRightRailOpen}
        phase={phase}
        guestCapabilityCaps={guestCapabilityCaps}
        onRightScroll={onRightScroll}
        hostLiveKitParticipant={hostLiveKitParticipant}
        liveKitMediaEpoch={liveKitMediaEpoch}
        sessionTitle={sessionTitle}
        guestMembersGridSelf={guestMembersGridSelf}
        guestClassmatesPeers={guestClassmatesPeers}
        sessionId={sessionId}
        guestNotesCurrentSceneRef={guestNotesCurrentSceneRef}
        onGuestCaptureSmartboard={onGuestCaptureSmartboard}
        onGuestNotesJumpToScene={onGuestNotesJumpToScene}
        liveMediaCheck={liveMediaCheck}
        liveMediaDiagTick={liveMediaDiagTick}
        roomRef={roomRef}
        guestJoyKitDrive={guestJoyKitDrive}
        tryStartLiveKitPlayback={tryStartLiveKitPlayback}
        antennaSoloMode={antennaSoloMode}
        liveParticipants={liveParticipants}
        setAntennaSoloMode={setAntennaSoloMode}
        setPromotedId={setPromotedId}
        liveDuration={liveDuration}
        arenaHostCameraCenter={arenaHostCameraCenter}
        lhHostShowsRemoteMain={lhHostShowsRemoteMain}
        rightRailShowsLocalHost={rightRailShowsLocalHost}
        setHostRightRailLocalVideoOpen={setHostRightRailLocalVideoOpen}
        showHostRightRailVideoFrame={showHostRightRailVideoFrame}
        hostVidHeight={hostVidHeight}
        videoFxActive={videoFxActive}
        videoFilterCSS={videoFilterCSS}
        arenaLayoutMode={arenaLayoutMode}
        applyHostArenaLayoutMode={applyHostArenaLayoutMode}
        lhMainRemoteParticipant={lhMainRemoteParticipant}
        livekitParticipantsMap={livekitParticipantsMap}
        cameraOn={cameraOn}
        promotedId={promotedId}
        user={user}
        hostRightRailVideoIsCenterCameraOnly={hostRightRailVideoIsCenterCameraOnly}
        guestMicLocked={guestMicLocked}
        toggleMic={toggleMic}
        micOn={micOn}
        guestCamLocked={guestCamLocked}
        toggleCamera={toggleCamera}
        guestScreenShareLocked={guestScreenShareLocked}
        toggleScreenShare={toggleScreenShare}
        sharingScreen={sharingScreen}
        debateArena={debateArena}
        liriAudioScenes={liriAudioScenes}
        liriAudioInitialSceneIndex={liriAudioInitialSceneIndex}
        persistLiriSceneIndex={persistLiriSceneIndex}
        debateModBusy={debateModBusy}
        debatePatch={debatePatch}
        debateAiWeightPctDisplay={debateAiWeightPctDisplay}
        onDebateAiWeightRangeChange={onDebateAiWeightRangeChange}
        debateCurrentRoundStatus={debateCurrentRoundStatus}
        debateOpenVoting={debateOpenVoting}
        debateCloseVoting={debateCloseVoting}
        debateLiveVoteCounts={debateLiveVoteCounts}
        debateAiJudgeBusy={debateAiJudgeBusy}
        debateRunAiJudge={debateRunAiJudge}
        debateAiReportPreview={debateAiReportPreview}
        recording={recording}
        recError={recError}
        stopRecording={stopRecording}
        setRecError={setRecError}
        hostBoardRightRailTools={hostBoardRightRailTools}
        hostWbToolsRail={hostWbToolsRail}
        hostWhiteboardPagingForRail={hostWhiteboardPagingForRail}
        mmCardVisible={mmCardVisible}
        setMmCardVisible={setMmCardVisible}
        mmView={mmView}
        setMmView={setMmView}
        step={step}
        stepCount={stepCount}
        activeEtapes={activeEtapes}
        gotoStep={gotoStep}
        sessionCommFlags={sessionCommFlags}
        guestMultilangConfig={guestMultilangConfig}
        guestLivekitInterpreterParticipants={guestLivekitInterpreterParticipants}
        guestLivekitInterpreterVolume={guestLivekitInterpreterVolume}
        setGuestLivekitInterpreterVolume={setGuestLivekitInterpreterVolume}
        guestMultilangViewLang={guestMultilangViewLang}
        setGuestMultilangViewLang={setGuestMultilangViewLang}
        guestMultilangRolling={guestMultilangRolling}
        guestTeacherTranscript={guestTeacherTranscript}
        guestTeacherTranscriptPartial={guestTeacherTranscriptPartial}
        supabase={supabase}
        curEtape={curEtape}
        chatMessages={chatMessages}
        publishGuestLongiaBusEvent={publishGuestLongiaBusEvent}
        guestLongiaSessionDigests={guestLongiaSessionDigests}
        toast={toast}
        guestMultilangBrowserTtsOn={guestMultilangBrowserTtsOn}
        setGuestMultilangBrowserTtsOnPersist={setGuestMultilangBrowserTtsOnPersist}
        guestMultilangEdgeTtsOn={guestMultilangEdgeTtsOn}
        setGuestMultilangEdgeTtsOnPersist={setGuestMultilangEdgeTtsOnPersist}
        assertGuestLongiaSignal={assertGuestLongiaSignal}
        guestMeshGrant={guestMeshGrant}
        guestMeshRemainSec={guestMeshRemainSec}
        guestMediaDrive={guestMediaDrive}
        sessionFormationId={sessionFormationId}
        msMode={msMode}
        setMsMode={setMsMode}
        nqAnalysis={nqAnalysis}
        msBody={msBody}
        msTyped={msTyped}
      />
    </div>
  );
});
